services:  
  mysql:
    container_name: mysql-serviceflow
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: serviceflow
      MYSQL_USER: serviceflow
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database/db:/var/lib/mysql
    
  php:
    container_name: php-serviceflow
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - '8191:80'
    
  # node:
  #   container_name: node-serviceflow
  #   image: "node:18"
  #   user: "node"
  #   working_dir: /var/www/html/frontend
  #   environment:
  #     - NODE_ENV=debug
  #   volumes:
  #     - ./frontend:/var/www/html/frontend
  #   # expose:
  #   #   - "8081"
  #   ports:
  #     - '8192:8080'
  #   command: "npm run serve"

  phpmyadmin:
    container_name: phpmyadmin-serviceflow
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql  # Use o nome do serviço do MySQL
      MYSQL_ROOT_PASSWORD: 12345678  # Use a senha do root do MySQL
    ports:
      - '8190:80'  # Mapeie a porta do phpMyAdmin para a porta desejada
    # networks:
    #   - serviceflow-network